### ISSUE TITLE
is the problem "CompatibleFieldSerializer fails with IndexOutOfBoundsException on field removal" fixed?

### ISSUE THREAD

**Issue by jackjoesh** [EsotericSoftware/kryo#868] opened 2021-11-16 19:09 UTC
Regard to the problem  "CompatibleFieldSerializer fails with IndexOutOfBoundsException on field removal" (https://github.com/EsotericSoftware/kryo/issues/286),  I found still existed in kryo 4.0.2.
Is this problem fixed in kryo5? Thank you!

**Comment by theigl** [comment] 2021-11-17 10:33
@jackjoesh: I honestly have no idea. This issue was long before I took over maintaining this project. You'll have to try to reproduce it against the latest version. If the problem still exists, please provide a reproducer against Kryo 5.

**Comment by theigl** [comment] 2021-11-17 21:14
It looks like this was fixed in Kryo 5.0.0-RC1: https://github.com/EsotericSoftware/kryo/commit/a532b110ddf38efe2d6a1a8b56153d7bbf403542

I'll close this issue for now. Please re-open if the problem still occurs with recent Kryo versions.

**Closed by theigl** 2021-11-17 21:14 UTC
Labels: question
