### ISSUE TITLE
Allowing to get some delta when testing equality between floats or doubles

### ISSUE THREAD

**Issue by pgrt** [EsotericSoftware/kryo#830] opened 2021-05-18 11:39 UTC
Hello,

In a clean debian/unstable chroot, the some tests are not passing because floats or doubles are compared by assertEquals but no delta is allowed, although there should be as the float 0 may have various representations. The attached patch solves these issues.
[testing_floats_doubles_equality.txt](https://github.com/EsotericSoftware/kryo/files/6500963/testing_floats_doubles_equality.txt)

**Environment:**
 - OS:Debian/unstable
 - JDK Version: 11
 - Kryo Version: 5.1.0

Best regards,
Pierre

**Comment by theigl** [comment] 2021-05-18 12:55
@pgrt: Thank you for reporting this! Could you provide a PR instead of a patch?

**Comment by pgrt** [comment] 2021-05-18 13:03
Hi,
Sure! Yet my fix is unfortunately quite poor, just commenting out as I have no precise idea of the real problem. Well, I will submit a PR and then we can talk again about it.

**Comment by theigl** [comment] 2021-06-03 11:09
Closing until somebody else runs into this or we can determine the root cause.

**Closed by theigl** 2021-06-03 11:09 UTC
Labels: bug, needs repro
