### ISSUE TITLE
@Bind (FieldSerializerAnnotationsUtil) does not pass field type to serializer constructor 

### ISSUE THREAD

**Issue by tweise** [EsotericSoftware/kryo#310] opened 2015-05-25 04:02 UTC
Instead of field.getClass() it should be field.getType() in

https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/FieldSerializerAnnotationsUtil.java#L69

```
Serializer s = ReflectionSerializerFactory.makeSerializer(fieldSerializer.getKryo(), serializerClass, field.getClass());
```

**Comment by magro** [comment] 2016-03-28 23:55
Sorry for the late response, is this still relevant? If so, can you elaborate the issue?

**Comment by magro** [comment] 2016-04-08 23:14
Please reopen if still relevant.

**Comment by tweise** [comment] 2016-04-09 17:47
@magro The bug is still there. Instead of passing the type of field, java.lang.reflect.Field is passed to makeSerializer (which expects the type). I don't see a way to reopen the issue, can you please do it.

**Comment by magro** [comment] 2016-04-09 18:16
Ok. Do you want to submit a pull request?

**Comment by magro** [comment] 2016-08-27 22:12
@tweise can you tell what the consequence of the issue is? How could it be reproduced?

**Comment by baltiyskiy** [comment] 2018-04-17 13:45
I've just ran into exactly the same issue. The consequence is that FieldSerializer is instantiated for type `Field` instead of the proper element type, so the elements don't get serialized. That's pretty broken.

**Comment by baltiyskiy** [comment] 2018-04-17 19:16
The tests didn’t catch this because BindCollection was only tested with LongArraySerializer, which doesn’t accept element class in the constructor. Actually, there should be more tests for CollectionBind and other binds with different serializers, but I think it’s out of scope for this issue.

**Comment by magro** [comment] 2018-06-07 21:36
@NathanSweet Is this fixed in the 5.0 branch already?

**Comment by NathanSweet** [comment] 2018-06-08 01:35
It should be now!

**Closed** 2018-06-14 22:41 UTC
