### ISSUE TITLE
Unable to serialize class with generics

### ISSUE THREAD

**Issue by mrniko** [EsotericSoftware/kryo#703] opened 2019-11-06 12:56 UTC
I'm getting follow exception:

```java
com.esotericsoftware.kryo.KryoException: Unable to resolve type variable: A

	at com.esotericsoftware.kryo.util.GenericsUtil.resolveTypeVariable(GenericsUtil.java:112)
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveType(GenericsUtil.java:41)
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:294)
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:259)
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:273)
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:259)
	at com.esotericsoftware.kryo.serializers.CachedFields.addField(CachedFields.java:139)
	at com.esotericsoftware.kryo.serializers.CachedFields.rebuild(CachedFields.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:82)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:124)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:108)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:395)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:380)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:87)
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:500)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:110)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:532)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
```

Code to reproduce:

```java
    public interface Test2<A, B, C, D> extends Serializable {

        void test(A a, B b);

    }

    public static class BaseTest<C, D> {

    }

    public static class Test1<A, B, C, D> extends BaseTest<C, D> {

        protected Test2<A, B, C, D> test;

    }

        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        Output output = new Output(8192, -1);
        kryo.writeClassAndObject(output, new Test1<>());
```

Used JDK 1.8, Kryo 5.0.0-RC4

**Comment by theigl** [comment] 2019-11-08 08:45
This is most likely a duplicate of #655

**Comment by Tostino** [comment] 2019-12-26 18:47
I am getting a similar error, however https://github.com/EsotericSoftware/kryo/pull/685 did not fix the issue for me.

**Comment by Tostino** [comment] 2019-12-26 20:15
I created a pull request to add an extra test which captures the error I have with my production workload when trying to upgrade: https://github.com/EsotericSoftware/kryo/pull/707

**Comment by theigl** [comment] 2020-05-16 12:49
@mrniko: Could you please close this issue? I just verified that this is the same as #655 and will add a PR with a simplified testcase.

**Comment by mrniko** [comment] 2020-05-16 14:14
Did you try my testcase too?

**Comment by theigl** [comment] 2020-05-16 14:43
Yes. Both test cases produce the exact same error and both test cases can be fixed by the same workaround.

**Closed** 2020-05-16 14:57 UTC

**Comment by theigl** [comment] 2020-05-16 18:40
Should be fixed in RC6. Please verify.
