### ISSUE TITLE
Consider importing some of the default serialisers from the kryo-serialisers project

### ISSUE THREAD

**Issue by mikehearn** [EsotericSoftware/kryo#376] opened 2015-12-10 14:57 UTC
In particular, it'd be nice to have the collections and ArrayAsListSerialiser. I just wasted some time trying to fix serialisation of an object tree that contains an Arrays.asList until I realised this problem was solved already in an extensions project. Why not include this by default?

**Comment by magro** [comment] 2016-08-27 22:04
Sorry for the late response! The ArraysAsListSerialiser is not included by default because it uses unsafe (reflection based) access to the underlying list, which could break on jvms that we don't have in our CI setup.

Perhaps we should reconsider this policy, because it probably would help more users than the potential issue would affect (and these users should get an error that directly points out the issue caused by reflection).

@NathanSweet @romix WDYT?

**Comment by magro** [comment] 2016-08-27 22:05
Related: #380

**Comment by NathanSweet** [comment] 2018-06-09 05:42
Closed by #151

**Closed by NathanSweet** 2018-06-09 05:42 UTC
