### ISSUE TITLE
JVM crash

### ISSUE THREAD

**Issue by iody** [EsotericSoftware/kryo#426] opened 2016-05-27 08:52 UTC
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f34557853c9, pid=29862, tid=139861403088640

hi anyone had an idea why is this happening?

#
# JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 2922 C2 com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeStringField.write(Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;)V (19 bytes) @ 0x00007f34557853c9 [0x00007f34557853a0+0x29]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
```

**Comment by iody** [comment] 2016-05-27 08:57
```

Current thread (0x00007f341005f800):  JavaThread "rmqio-2" [_thread_in_Java, id=30201, stack(0x00007f34052fb000,0x00007f34053fc000)]

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=1 (SEGV_MAPERR), si_addr=0x0000000000000009

Registers:
RAX=0x00000000b336bfe0, RBX=0x00000000b336bd30, RCX=0x00000000eda6f450, RDX=0x00000000edaf6088
RSP=0x00007f34053fa320, RBP=0x00000000edb8c320, RSI=0x00000000edb8c2b0, RDI=0x00007f341005f800
R8 =0x0000000000000003, R9 =0x0000000000005300, R10=0x0000000000000014, R11=0x0000000000000001
R12=0x0000000000000000, R13=0x00007f345579e844, R14=0x00007f34053fa330, R15=0x00007f341005f800
RIP=0x00007f34557853c9, EFLAGS=0x0000000000010202, CSGSFS=0x000000000000e033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f34053fa320)
0x00007f34053fa320:   0000000000000000 00007f3400000000
0x00007f34053fa330:   00000000edb8c320 00007f345579e810
0x00007f34053fa340:   00000000c14215c0 00000000c126aae0
0x00007f34053fa350:   00000000edaf6088 00000000eda6f450
0x00007f34053fa360:   edb8c32000000000 0000000000000003
0x00007f34053fa370:   00007f34557912b8 00000000c1591e38
0x00007f34053fa380:   00000000c126aae0 00007f3455791358
0x00007f34053fa390:   00000000c14215c0 00000000c126aae0
0x00007f34053fa3a0:   00000000c1591868 00000000edaf6088
0x00007f34053fa3b0:   00000000ed7b2800 00000000eda6f450
0x00007f34053fa3c0:   00000000c14215c0 00000000b00021c0
0x00007f34053fa3d0:   0000000000000000 00007f34053fa458
0x00007f34053fa3e0:   00000000c1590fd0 00007f345579e810
0x00007f34053fa3f0:   00000000c1590f70 00000000c126aae0
0x00007f34053fa400:   00000000edaf6088 00000000ed7b2800
0x00007f34053fa410:   c1590fd000000000 00007f3400000003
0x00007f34053fa420:   00000000c126b1d8 00007f345579a7dc
0x00007f34053fa430:   00007f34053fa4a8 00007f3455006058
0x00007f34053fa440:   00007f3455006058 00000000ed7b2800
0x00007f34053fa450:   00000000edaf6088 00000000c126aae0
0x00007f34053fa460:   00000000c1590f70 00007f34053fa468
0x00007f34053fa470:   00000000b29cf3cb 00007f34053fa4d0
0x00007f34053fa480:   00000000b2a37308 00000000b37c1908
0x00007f34053fa490:   00000000b29cf458 00007f34053fa448
0x00007f34053fa4a0:   00007f34053fa4c0 00007f34053fa518
0x00007f34053fa4b0:   00007f3455006058 0000000000000000
0x00007f34053fa4c0:   00000000ed7b2800 00000000edaf6088
0x00007f34053fa4d0:   00000000c126aae0 00007f34053fa4d8
0x00007f34053fa4e0:   00000000b3320582 00007f34053fa598
0x00007f34053fa4f0:   00000000b3320f90 00000000b37c0020
0x00007f34053fa500:   00000000b3320880 00007f34053fa4c0
0x00007f34053fa510:   00007f34053fa590 00007f34053fa5e0 

Instructions: (pc=0x00007f34557853c9)
0x00007f34557853a9:   b3 25 8b ff 66 66 90 89 84 24 00 c0 fe ff 55 48
0x00007f34557853b9:   83 ec 10 4c 8b 56 10 46 8b 1c 11 45 85 db 74 47
0x00007f34557853c9:   45 8b 43 08 41 81 f8 00 ae 00 b0 75 22 4d 8b d3
0x00007f34557853d9:   48 85 d2 74 37 48 8b f2 49 8b d2 66 66 90 e8 04 

Register to memory mapping:

RAX=0x00000000b336bfe0 is an top
{instance class} 
 - klass: {other class}
RBX=0x00000000b336bd30 is an top
{method} 
 - klass: {other class}
RCX=0x00000000eda6f450 is an top
java.util.LinkedHashMap 
 - klass: 'java/util/LinkedHashMap'
RDX=0x00000000edaf6088 is an top
com.esotericsoftware.kryo.io.Output 
 - klass: 'com/esotericsoftware/kryo/io/Output'
RSP=0x00007f34053fa320 is pointing into the stack for thread: 0x00007f341005f800
RBP=0x00000000edb8c320 is an top
[Lcom.esotericsoftware.kryo.serializers.FieldSerializer$CachedField; 
 - klass: 'com/esotericsoftware/kryo/serializers/FieldSerializer$CachedField'[]
 - length: 3
RSI=0x00000000edb8c2b0 is an top
com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeStringField 
 - klass: 'com/esotericsoftware/kryo/serializers/UnsafeCacheFields$UnsafeStringField'
RDI=0x00007f341005f800 is a thread
R8 =0x0000000000000003 is an unknown value
R9 =0x0000000000005300 is an unknown value
R10=0x0000000000000014 is an unknown value
R11=0x0000000000000001 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x00007f345579e844 is at entry_point+260 in (nmethod*)0x00007f345579e5d0
R14=0x00007f34053fa330 is pointing into the stack for thread: 0x00007f341005f800
R15=0x00007f341005f800 is a thread


Stack: [0x00007f34052fb000,0x00007f34053fc000],  sp=0x00007f34053fa320,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 2922 C2 com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeStringField.write(Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;)V (19 bytes) @ 0x00007f34557853c9 [0x00007f34557853a0+0x29]
J 2883 C2 com.esotericsoftware.kryo.serializers.FieldSerializer.write(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;)V (122 bytes) @ 0x00007f345579e810 [0x00007f345579e740+0xd0]
J 2845 C2 com.esotericsoftware.kryo.serializers.ObjectField.write(Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;)V (420 bytes) @ 0x00007f3455791358 [0x00007f3455791180+0x1d8]
J 2883 C2 com.esotericsoftware.kryo.serializers.FieldSerializer.write(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;)V (122 bytes) @ 0x00007f345579e810 [0x00007f345579e740+0xd0]
j  com.esotericsoftware.kryo.Kryo.writeObject(Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;)V+131
```

**Comment by magro** [comment] 2016-05-27 10:26
How can it be reproduced?

**Comment by iody** [comment] 2016-05-30 08:44
im serialzing huge hash map of string with up to 1.2 million objects simultaneously. could this be an effect of using same kryo instance for each object? 

or do i need to created new kryo instance each time to serialise an object?

**Comment by magro** [comment] 2016-05-30 14:57
Not sure what you mean with "simultaneously". A Kryo instance must be used by a single thread at a time only, not by multiple threads concurrently. If in doubt just share some code that shows how you're using it.

**Comment by iody** [comment] 2016-06-08 09:28
the kryo instance is inside an actor(akka).  which received messages.

 let me try to create a new instance each time the method in the actor is use.

**Comment by romix** [comment] 2016-06-08 14:58
@iody You can have one kryo instance per actor, e.g. as a thread local variable, or you can use kryo instances pooling and borrow a kryo instance from the pool for the duration of your serialization/deserialization operation. 

BTW, if you use Kryo with Akka, have you seen https://github.com/romix/akka-kryo-serialization?

**Comment by iody** [comment] 2016-06-09 02:31
hmm does it has something to do with the crash of unsafe fields?

com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeStringField.write(Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;

**Comment by iody** [comment] 2016-06-09 09:50
i already close-

but still getting this at times:


# J 1509 C2 com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Lcom/esotericsoftware/kryo/io/Output;Ljava/lang/Object;Lcom/esotericsoftware/kryo/Serializer;)V (246 bytes) @ 0x00007f405d510f44 [0x00007f405d510e80+0xc4]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp

**Comment by magro** [comment] 2016-06-09 22:21
Can you test with the kryo SNAPSHOT?

**Comment by XYangX** [comment] 2016-06-15 01:23
I got the same wrong...

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcd3d15534f, pid=13490, tid=140519155640064
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 138 C1 java.lang.String.length()I (6 bytes) @ 0x00007fcd3d15534f [0x00007fcd3d155320+0x2f]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

**Comment by magro** [comment] 2016-06-15 06:01
Missing information. Which kryo version are you using? Can you test with the kryo SNAPSHOT?

**Comment by magro** [comment] 2016-06-15 06:02
And please provide a reproducer.

**Comment by iody** [comment] 2016-07-01 03:16
I'm using 3.0.3

**Comment by magro** [comment] 2016-07-01 19:06
Can you create a long running test that creates mass number of messages?

**Comment by magro** [comment] 2016-08-27 21:51
Is this still an issue for you?

**Comment by tetv** [comment] 2016-08-29 16:46
I am having also a JVM random crashes using Kryo 4.0.0 in a vertx application using codecs.
Basically, the Kryo is only used to convert `Object` to `byte[]` and vice versa.
Before I was using Jackson to convert `Object` to **json** and everything was running fine (never experienced a JVM crash).
The reason of moving to Kryo was to increase dramatically performance (Kryo is 90% faster).

You have mentioned that Kryo is not Thread-Safe. (Maybe the issue is there).
Even to do just a simple conversion between `Object` to `byte[]`, is it not possible to use a `static` instance of Kryo in a multi thread environment? If not, can you suggest alternatives of dealing with that issue?

**Comment by magro** [comment] 2016-08-29 20:08
@tetv I suggest the README: https://github.com/EsotericSoftware/kryo#pooling-kryo-instances - HTH :-)

**Comment by tetv** [comment] 2016-08-30 16:01
It seems that is working fine now. Many thanks.

**Comment by magro** [comment] 2016-08-30 16:38
@tetv great!

**Closed** 2017-01-04 18:22 UTC

**Comment by rohts-patil** [comment] 2019-08-28 11:00
Hey @tetv ,
How did you fix this? I am facing this error for while now.

**Comment by Mitisky** [comment] 2020-04-09 04:08
@rohts-patil Kryo is not thread safe class.My suggestion is that review your code and avoid thread conflict.
