### ISSUE TITLE
Issue BufferUnderflow when InputChunked and OutputChunked is used with hazelcast serlization.

### ISSUE THREAD

**Issue by asadyarkhan007** [EsotericSoftware/kryo#891] opened 2022-03-25 07:07 UTC
**Describe the bug**
I am having issues when I try to use InputChunked and OutputChunked in serialization classes I get the following error.

```
com.esotericsoftware.kryo.KryoException: Unable to read chunk size.
Serialization trace:
id (com.abc.store.serializer.EmployeeSerializerClassTest$Employee)

	at com.esotericsoftware.kryo.io.InputChunked.readChunkSize(InputChunked.java:95)
	at com.esotericsoftware.kryo.io.InputChunked.fill(InputChunked.java:76)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:216)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:337)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:850)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:132)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:777)
	at com.abc.store.serializer.EmployeeSerializerClassTest$EmployeeSerializer.read(EmployeeSerializerClassTest.java:105)
	at com.abc.store.serializer.EmployeeSerializerClassTest.givenObject_whenSerializing_thenReadCorrectly(EmployeeSerializerClassTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.io.EOFException
```

**To Reproduce**
```

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.InputChunked;
import com.esotericsoftware.kryo.io.OutputChunked;
import com.esotericsoftware.kryo.util.Pool;
import com.hazelcast.internal.serialization.InternalSerializationService;
import com.hazelcast.internal.serialization.SerializationService;
import com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder;
import com.hazelcast.internal.serialization.impl.ObjectDataInputStream;
import com.hazelcast.internal.serialization.impl.ObjectDataOutputStream;
import com.hazelcast.nio.ObjectDataInput;
import com.hazelcast.nio.ObjectDataOutput;
import com.hazelcast.nio.serialization.StreamSerializer;
import org.junit.Assert;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;


public class EmployeeSerializerClassTest {

    private static Kryo kryo = new Kryo();
    private static InputChunked input;
    private static OutputChunked output;

    private static EmployeeSerializer employeeSerializer = new EmployeeSerializer();


    public static void main(String[] args) throws IOException {
        kryo.register(Employee.class);
        output = new OutputChunked(new FileOutputStream("file1.dat"));
        input  = new InputChunked(new FileInputStream("file1.dat"));

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        SerializationService serializationService = new DefaultSerializationServiceBuilder().build();
        ObjectDataOutput odo = new ObjectDataOutputStream(bos, (InternalSerializationService) serializationService);
        Employee employee1 = new Employee();
        employee1.setName("identity");
        employeeSerializer.write(odo, employee1);
        bos.writeTo(output);
        output.close();

        ByteArrayInputStream bis = new ByteArrayInputStream(input.getInputStream().readAllBytes());
        SerializationService serializationService2 = new DefaultSerializationServiceBuilder().build();
        ObjectDataInputStream objectDataInputStream = new ObjectDataInputStream(bis, (InternalSerializationService) serializationService2);
        Employee employee2 = employeeSerializer.read(objectDataInputStream);

        input.close();

        Assert.assertEquals("identity", employee2.getName());
    }

    /**
     * Employee class needs to be serialized
     */
    public static class EmployeeSerializer implements StreamSerializer<Employee> {
        /**
         * Object pool for the Kryo instances.
         */
        private final Pool<Kryo> kryoPool = new Pool<Kryo>(true, true) {
            protected Kryo create() {
                Kryo kryo = new Kryo();
                kryo.register(Employee.class);
                return kryo;
            }
        };

        /**
         * {@inheritDoc}
         */
        @Override
        public void write(ObjectDataOutput objectDataOutput, Employee employee) {
            Kryo kryo = kryoPool.obtain();
            OutputChunked output = new OutputChunked((OutputStream) objectDataOutput);
            kryo.writeObject(output, employee);
            output.endChunk();
            output.flush();
            kryoPool.free(kryo);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Employee read(ObjectDataInput objectDataInput) {
            InputStream in = (InputStream) objectDataInput;
            InputChunked input = new InputChunked(in);
            Kryo kryo = kryoPool.obtain();
            Employee employee = kryo.readObject(input, Employee.class);
            kryoPool.free(kryo);
            return employee;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public int getTypeId() {
            return 5;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public void destroy() {
            StreamSerializer.super.destroy();
        }

    }

    /**
     * Employee class needs to be serialized
     */
    public static class Employee {
        Integer id;
        String name;

        public Integer getId() {
            return id;
        }

        public void setId(Integer id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
}

```

**Environment:**
 - OS: Macos
 - JDK Version: 11
 - Kryo Version: 5.2.0
 - hazelcast: 4.2.4

**Additional context**

**Comment by asadyarkhan007** [comment] 2022-03-25 07:42
If I change InputChunked to Input and OutputChunked to Output classes The Unit test successfully runs. The problem is we are using some different implementation and we need to use InputChunked and OutputChunked and that's why we are getting better performance with Chunked implementation. Please let me know why it is failing... is there any issue with Kryo...

**Comment by theigl** [comment] 2022-03-25 10:09
@asadyarkhan007: Please adjust the reproducer test-case to work without Hazelcast and Spring, so I can simply run it as a unit test in Kryo.

**Comment by asadyarkhan007** [comment] 2022-03-25 10:24
@theigl removed Spring dependency but can not remove hazelcast dependency.

**Comment by asadyarkhan007** [comment] 2022-03-25 10:42
Kryo works fine without hazelcast I have added the code below but what is the purpose if we can't use with hazelcast or any other third-party. can you look the above code it is easy to run just copy and past and add hazelcast 4.2.4 library from maven.

```
public class EmployeeKyroTestWithoutHazelcast {

        private static Kryo kryo = new Kryo();
        private static InputChunked input;
        private static OutputChunked output;


        public static void main(String[] args) throws IOException {
            kryo.register(Employee.class);
            output = new OutputChunked(new FileOutputStream("file1.dat"));
            input = new InputChunked(new FileInputStream("file1.dat"));

            Employee employee1 = new Employee();
            employee1.setName("identity");
            kryo.writeObject(output, employee1);
            output.endChunk();
            output.flush();
            output.close();

            Employee employee2 = kryo.readObject(input,Employee.class);
            input.close();
            System.out.println(employee1.getName());
            System.out.println(employee2.getName());
            Assert.assertEquals(employee1.getName(), employee2.getName());
        }

        /**
         * Employee class needs to be serialized
         */
        public static class Employee {
            Integer id;
            String name;

            public Integer getId() {
                return id;
            }

            public void setId(Integer id) {
                this.id = id;
            }

            public String getName() {
                return name;
            }

            public void setName(String name) {
                this.name = name;
            }
        }
}

```

**Comment by theigl** [comment] 2022-03-25 10:56
@asadyarkhan007: Since this works without Hazelcast, this is not an issue with Kryo but with your integration. I don't have the time to debug third party integrations. 

What you can do is enable [debug logging](https://github.com/EsotericSoftware/kryo#logging) for the plain Kryo version *and* for your Hazelcast integration and then compare the logs. There has to be some subtle difference in how the data is written.

**Comment by theigl** [comment] 2022-04-14 10:10
Closing this for now. Please re-open if you can reproduce this issue with plain Kryo.

**Closed by theigl** 2022-04-14 10:10 UTC
Labels: bug, needs repro
