### ISSUE TITLE
ByteBufferInput read string failed for DirectByteBufferR.

### ISSUE THREAD

**Issue by eyinsma** [EsotericSoftware/kryo#595] opened 2018-05-29 15:57 UTC
I use off-heap cache with Kryo, and returned bytebuffer from off-heap cache is a readonly bytebuffer. In this case the BytebufferInput read string failed. 

~~~
	at java.nio.DirectByteBufferR.put(DirectByteBufferR.java:309)
	at com.esotericsoftware.kryo.io.ByteBufferInput.readAscii(ByteBufferInput.java:641)
	at com.esotericsoftware.kryo.io.ByteBufferInput.readString(ByteBufferInput.java:503)
~~~

Checked the code, I think to update the original bytebuf can be avoided, right?  Is that possible for Kyro to support the read only bytebuffer input?

**Comment by NathanSweet** [comment] 2018-06-02 15:30
Kryo avoids writing the length for 7-bit ASCII strings, instead using the
8th bit as a flag to denote the end of the string. In order to efficiently
read the ASCII string, "new String(byte, int, int, int)" is used. The last
byte needs to be modified so that constructor can copy it, then it is
modified back.

There is currently not a way to avoid this, short of modifying the Kryo
source. It is one of the issues I'd like to address in the kryo-5.0.0-dev
branch. Unfortunately it means something needs to get worse: either the
serialized bytes get larger (by one byte per ASCII string) or
deserialization gets slower (to copy the bytes to a temporary buffer). It's
probably not worth making it configurable.

**Comment by NathanSweet** [comment] 2018-06-03 07:57
The kryo-5.0.0-dev branch no longer modifies the buffer when reading ASCII
strings.
https://github.com/EsotericSoftware/kryo/commit/8d78e012d1d2453177e2461e19bab47242dc9ab9

**Comment by eyinsma** [comment] 2018-06-04 05:44
Thanks, Nathan. That's what I want.

**Comment by NathanSweet** [comment] 2018-06-08 23:03
No, that is the only instance the buffer is modified. Closing since it is fixed in dev branch.

**Closed by NathanSweet** 2018-06-08 23:03 UTC

**Comment by oehme** [comment] 2019-12-05 09:54
This doesn't work in 5.0.0-RC4, because `BufferInput` still uses mutating methods like `Buffer.compact`.

**Comment by NathanSweet** [comment] 2020-03-07 11:31
@oehme Buffer/ByteBuffer is stateful and not thread safe. Each thread needs their own ByteBufferInput and ByteBufferOutput, and each needs their own ByteBuffer. You can have multiple ByteBuffers for the same memory using ByteBuffer methods like `slice` or `wrap`.

**Comment by oehme** [comment] 2020-03-07 13:36
The problem is that many frameworks (like websockets) use read-only bytebuffers. With Kryo I have to make copies of those buffers, since Kryo tries to mutate them. This leads to unnecessary garbage and CPU cycles. Kryo should be able to use read-only buffers for reading.

**Comment by paplorinc** [comment] 2020-09-24 07:11
Hey @NathanSweet, does Kryo 5 accept readonly inputs reliably now?

**Comment by theigl** [comment] 2020-09-25 09:30
@paplorinc: There have been no further improvements for read-only buffers in Kryo 5. 

I experimentally changed our [roundtrip serialization tests](https://github.com/EsotericSoftware/kryo/blob/643ea0e94e553a6e5744e6980f472e490d1f4568/test/com/esotericsoftware/kryo/KryoTestCase.java#L147) to use read-only buffers and all tests pass:

```
@Override
public Input createInput (byte[] buffer) {
	ByteBuffer byteBuffer = allocateByteBuffer(buffer);
	return new ByteBufferInput(byteBuffer.asReadOnlyBuffer());
}
```

Can you provide a test-case that fails with read-only buffers?

**Comment by oehme** [comment] 2020-09-27 18:41
ByteBufferInput still calls `ByteBuffer.compact` in the `require` method, which is called e.g. when calling `readBytes`. So just looking at the code I can tell that this won't work with read-only buffers. I guess your roundtrip test doesn't test `readBytes`? Also, since it's not automated (you had to manually experiment), there is nothing preventing this from breaking again. See the discussion above where it was claimed that this was "the only instance the buffer is modifed" - This is definitely no longer true.

**Comment by theigl** [comment] 2020-09-27 19:27
@oehme: I'm open to improving this situation. I looked at the code as well and expected tests to fail because of the potential call to `compact` but none did. `readBytes` is called from dozens of tests but always returns before calling `compact` if the input is created from a `ByteBuffer`. If you can produce a failing test case for `new ByteBufferInput(readOnlyBuffer)`, we can take it from there.

> Also, since it's not automated (you had to manually experiment), there is nothing preventing this from breaking again. 

This is a good point. I'll add another configuration to the round-trip tests that uses a read-only buffer to make sure we don't break things in the future.

**Comment by theigl** [comment] 2020-09-27 19:47
Pushed https://github.com/EsotericSoftware/kryo/commit/74db64334d9e16de95562ccd3a33dc7050dbc939 to guard against breaking reading from read-only buffers.
