### ISSUE TITLE
The object can't be deserializer because the serializer not detect the real class

### ISSUE THREAD

**Issue by lucianogalvaodesousa** [EsotericSoftware/kryo#819] opened 2021-04-08 14:37 UTC
I report this bug in https://stackoverflow.com/questions/23962796/kryo-readobject-cause-nullpointerexception-with-arraylist/67006171#67006171

If I try deserializer the object of a classe company.HeaderReception occurs the NullPointerException, because when this object is serialized the field headers has in each value of yours keys a object serialized with classes company.HeaderRequest$1 and company.HeaderReception$1. The error on deserialization occurs on the method create of CollectionSerializer. The kryo can't instance the classes company.HeaderRequest$1 or company.HeaderReception$1 because trully it's is a ArrayList but when it was serialized the classes of values not detect the real class.

```
package company.helper;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import java.io.Serializable;
import java.util.*;
public class HeaderRequest implements Serializable {
    protected Map<String, List<String>> headers = new LinkedHashMap<>();
    private String idControleRequisicao;
    public HeaderRequest(String idControleRequisicao) {
        this.idControleRequisicao = idControleRequisicao;
        this.headers.put("idControleRequisicao", new ArrayList<String>(){{add(idControleRequisicao);}});
    }
    public String getIdControleRequisicao() {
        return idControleRequisicao;
    }
    public MultiValueMap<String, String> getHttpHeaders(){
       return new LinkedMultiValueMap<String, String>(this.headers);
    }
}

package company.helper;
import java.util.Arrays;
public class HeaderReception extends HeaderRequest{
    private String idControleRecepcao;
    public HeaderReception(String idControleRequisicao, String idControleRecepcao) {
        super(idControleRequisicao);
        this.idControleRecepcao = idControleRecepcao;
        if (idControleRecepcao != null) {
            this.headers.put("idControleRecepcao", Arrays.asList(idControleRecepcao));
        }
    }
    public String getIdControleRecepcao() {
        return idControleRecepcao;
    }
    
}

public class Test {
    public static void main(String[] args) {
    	HeaderReception headerObject = new HeaderReception(UUID.randomUUID().toString(),UUID.randomUUID().toString());
		Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(false);
        DefaultInstantiatorStrategy instanceStrategy = new DefaultInstantiatorStrategy();
        instanceStrategy.setFallbackInstantiatorStrategy(new StdInstantiatorStrategy());
		kryo.setInstantiatorStrategy(instanceStrategy);
		kryo.register(java.util.Arrays.asList().getClass(),new ArraysAsListSerializer());
		kryo.register(Collections.EMPTY_LIST.getClass(),new CollectionsEmptyListSerializer());
		kryo.register(Collections.EMPTY_MAP.getClass(),new CollectionsEmptyMapSerializer());
		kryo.register(Collections.EMPTY_SET.getClass(),new CollectionsEmptySetSerializer());
		//Serialize
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		Output output = new Output(baos);
		kryo.writeObject(output, headerObject);
		output.close();
		byte[] bytes = baos.toByteArray();
		//Deserialize
    	Input input = new Input(new ByteArrayInputStream(bytes));
    	HeaderReception headeObjectLoaded = kryo.readObject(input, HeaderReception.class);
    	System.out.println(headeObjectLoaded);
	}

}
```

**Comment by theigl** [comment] 2021-04-08 15:03
@lucianogalvaodesousa: The problem is the *anonymous* sub-class of `ArrayList`. I simplified your test to this:

```
public class Test {

	public static void main (String[] args) {
		HeaderRequest headerObject = new HeaderRequest(UUID.randomUUID().toString());
		Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(false);
		kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
		
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		Output output = new Output(out);
		kryo.writeObject(output, headerObject);
		output.close();

		Input input = new Input(new ByteArrayInputStream(out.toByteArray()));
		HeaderRequest headeObjectLoaded = kryo.readObject(input, HeaderRequest.class);
		System.out.println(headeObjectLoaded);
	}

	static class HeaderRequest implements Serializable {
	
		private final Map<String, List<String>> headers = new LinkedHashMap<>();
	
		public HeaderRequest (String id) {
			this.headers.put("id", new ArrayList<String>() {});
		}
	}
}
```

Are you using double-brace initialization in your production code? You really [shouldn't do that](https://blog.jooq.org/2014/12/08/dont-be-clever-the-double-curly-braces-anti-pattern/).

This is a bug, but I'm not sure it's worth trying to fix it. I can't think of any valid use case for anonymous sub-classes of `ArrayList`.

**Comment by lucianogalvaodesousa** [comment] 2021-04-08 23:01
Thank's for your answer. I don't knowed that the double braces generate a
anonymous class. Thank's for the link of explanation.

Em qui, 8 de abr de 2021 12:04, Thomas Heigl ***@***.***>
escreveu:

**Comment by lucianogalvaodesousa** [comment] 2021-04-08 23:08
After the explanation, I deleted the post in stackoverflow. Sorry about my error.

**Comment by theigl** [comment] 2021-04-09 10:29
@lucianogalvaodesousa: No problem! I'm closing this issue for now. If you remove the double-braces, everything should work as expected.

**Closed by theigl** 2021-04-09 10:29 UTC
Labels: bug, wontfix
