### ISSUE TITLE
Unable to serialise because of some issues `org.apache.commons.math3.stat.descriptive.DescriptiveStatistics`

### ISSUE THREAD

**Issue by akshay-hazari** [EsotericSoftware/kryo#901] opened 2022-06-21 09:38 UTC
I have overridden Kryo serialisation in my class, where it is unable to serialise DescriptiveStatistics from package org.apache.commons.math3.stat.descriptive.DescriptiveStatistics 

https://stackoverflow.com/questions/72570152/kryo-serialisation-error-while-serialising-org-apache-commons-math3-stat-descr

```
class DecimalDataCalculator(
  private var statsList: DescriptiveStatistics = DescriptiveStatistics()
) : KryoSerializable {

  override fun write(kryo: Kryo, output: Output) {
    try {
      log.info("DecimalData kryo write statsList: ${statsList.values.toList()}")
      log.info("DecimalData kryo write output : $output ")
      kryo.writeObject(output, statsList)
    } catch (e: Exception) {
      log.error("Failed to serialise Double Distribution", e)
      throw e
    }
  }

  override fun read(kryo: Kryo, input: Input) {
    val descriptiveStatistics: DescriptiveStatistics
    try {
      log.info("DecimalData kryo read statsList : ${this.statsList.values.toList()}")
      log.info("DecimalData kryo read input : $input")
      descriptiveStatistics = kryo.readObject(input, DescriptiveStatistics::class.java)
    } catch (e: Exception) {
      log.error("Failed to deserialize Double Distribution", e)
      throw e
    }
    statsList = descriptiveStatistics
  }
```
I get an exception on this line descriptiveStatistics = kryo.readObject(input, DescriptiveStatistics::class.java)

```
com.esotericsoftware.kryo.KryoException - Error constructing instance of class: org.apache.commons.math3.stat.descriptive.moment.FourthMoment
Serialization trace:
    moment (org.apache.commons.math3.stat.descriptive.moment.Kurtosis)
    kurtosisImpl (org.apache.commons.math3.stat.descriptive.DescriptiveStatistics)
```
Looking at the error I checked the class DescriptiveStatistics to find private UnivariateStatistic kurtosisImpl = new Kurtosis();

Seeing Kurtosis, it looks like this

```
public class Kurtosis extends AbstractStorelessUnivariateStatistic implements Serializable {
    private static final long serialVersionUID = 2784465764798260919L;
    protected FourthMoment moment;
    protected boolean incMoment;

    public Kurtosis() {
        this.incMoment = true;
        this.moment = new FourthMoment();
    }

    public Kurtosis(FourthMoment m4) {
        this.incMoment = false;
        this.moment = m4;
    }
```
Any Idea how I can go about serialising this DescriptiveStatistics

Any help is appreciated

**Comment by theigl** [comment] 2022-06-23 09:21
@akshay-hazari: Kryo supports (nearly) all JDK types out of the box. For complex third party classes, you might need to write a custom serializer. I don't have the capacity to debug issues with third party components. You can set a breakpoint in `DefaultInstantiatorStrategy` and check what the root cause of the exception is.

What's your Kryo configuration? It might be enough to use the [Objenesis instantiation strategy](https://github.com/EsotericSoftware/kryo#instantiatorstrategy).

**Comment by theigl** [comment] 2022-07-19 09:41
Closing this for now. If you can provide a simpler test-case, please re-open.

**Closed by theigl** 2022-07-19 09:41 UTC
Labels: bug, needs repro
