### ISSUE TITLE
JavaSerialiazation error with primitive types

### ISSUE THREAD

**Issue by techexplorer0310** [EsotericSoftware/kryo#922] opened 2022-10-07 10:38 UTC
When we use JavaSerialization and if the object being serialized has primitive fields like int, char etc then we can ClassNotFoundException for int.class. Earlier ObjectInputStream was used to resolveClass which was handling this. 
In the latest version ObjectInputStreamWithKryoClassLoader is used which does not handle this

**To Reproduce**
Use java serialization and read an object which has int field type.

**Environment:**
 - OS: All
 - JDK Version: 17
 - Kryo Version: 5.0

**Comment by theigl** [comment] 2022-10-30 09:35
@techexplorer0310: Could you please create reproducer for this issue?

**Comment by theigl** [comment] 2022-11-17 18:17
I briefly looked into this and it looks like that `ObjectInputStreamWithKryoClassLoader` should fall back on the default class loader instead of simply re-throwing the exception.

If you can't reproduce this issue in a simple test, could you register you own `JavaSerializer` that uses the following method to resolve class?

```java
		protected Class resolveClass (ObjectStreamClass type) {
			try {
				return Class.forName(type.getName(), false, kryo.getClassLoader());
			} catch (ClassNotFoundException ignored) {
				// ignored
			}
			try {
				return super.resolveClass(type);
			} catch (ClassNotFoundException ex) {
				throw new KryoException("Class not found: " + type.getName(), ex);
			} catch (IOException ex) {
				throw new KryoException("Could not load class: " + type.getName(), ex);
			}
		}
```

**Comment by theigl** [comment] 2022-11-21 15:42
Should be fixed. Please verify against the latest SNAPSHOT.

**Closed** 2022-11-21 15:42 UTC
Labels: bug, needs repro
