### ISSUE TITLE
Kryo is inefficiency to handle the object that it is without non-param constructor

### ISSUE THREAD

**Issue by maohui1993** [EsotericSoftware/kryo#422] opened 2016-05-06 02:12 UTC
when I handle the javax.naming.Reference, Kryo will wait in ConstructorAccess.get(type). Of course, i had seted kryo.setInstantiatorStrategy(...).
let see:
![lp 7g t55e sd2guv_n8u i](https://cloud.githubusercontent.com/assets/14193060/15062480/f3e2488c-1372-11e6-82d6-60e39a68b6c9.jpg)
![u7r 2p _9q4f6dvk v1czr](https://cloud.githubusercontent.com/assets/14193060/15062485/f89ed41c-1372-11e6-96b2-c97b7da0370d.png)

**Comment by magro** [comment] 2016-05-06 10:43
https://github.com/EsotericSoftware/reflectasm/blob/master/src/com/esotericsoftware/reflectasm/ConstructorAccess.java#L54 is `synchronized (loader)`, I think the following `accessClass = loader.loadClass(accessClassName);` can be tried once workout synchronization, and if this fails the synchronized block is executed. Do you want to submit a pull request with this for reflectasm?

@NathanSweet WDYT?

**Comment by magro** [comment] 2016-05-08 20:58
@maohui1993 Can you build reflectasm from [this branch](https://github.com/magro/reflectasm/tree/double-checked-accessClass) and use the related version (1.11.2-SNAPSHOT) in your app/project (explicitely add reflectasm as dependency) and see how it works?

**Comment by magro** [comment] 2016-05-08 22:13
@maohui1993 Now that reflectasm is released with the change you can just try the latest kryo SNAPSHOT (check [docs on SNAPSHOTs](https://github.com/EsotericSoftware/kryo#integration-with-maven)). How does it work for you?

**Comment by maohui1993** [comment] 2016-05-09 02:54
oh, I`m so sorry. recently, I busy at other thing, so I don`t observe your answer, so thanks.

year, I also think it is result of ** synchronized (loader)**, and I will test it .

**Comment by maohui1993** [comment] 2016-05-09 06:37
It is still inefficiency while I use reflectasm that its version(1.11.2).
![image](https://cloud.githubusercontent.com/assets/14193060/15105187/3059b81e-15f2-11e6-96e6-5d6b6b505ab4.png). And I try to delete the synchronized of the` protected synchronized java.lang.Class<?> loadClass()` that it is code in AccessClassLoader, bug it will wait in the line 91(ClassLoder.loderClass()). The threads will  preemption the same **classloader**  . Can I avoid synchronized, or make the loder become different?

**Comment by magro** [comment] 2016-05-09 07:08
@maohui1993 Yes, because there's a synchronized in class loading path threads will still be shown as blocked at some time (although `ClassLoader.loadClass` synchronizes on the class name). Are you sure that this (class loading) is a significant bottleneck besides the fact that threads are shown as blocked?

**Comment by maohui1993** [comment] 2016-05-09 08:32
year,I have resolved it by add a cache. And heartfelt thanks to you.

**Comment by magro** [comment] 2016-05-09 12:11
@maohui1993 Where have you added a cache?
Btw, now kryo snapshot includes the latest reflectasm with the removal of `synchronized` in `AccessClassLoader.loadClass`.

**Comment by maohui1993** [comment] 2016-05-10 01:39
Add in `ConstructorAccess.java`, the key is `accessClassName`, value is new `WeakReference(accessClass)`

**Comment by magro** [comment] 2016-05-10 18:45
@maohui1993 I saw https://github.com/magro/reflectasm/pull/1. The first `cacheMap.get(accessClassName).get();` is not taking part in synchronization, so the HashMap would be accessed concurrently from different threads and could get corrupted. It should probably be a ConcurrentHashMap. If you want to change it, can you share some benchmark numbers that show the difference? If possible the benchmark should be open source to be reproducable :-)

@NathanSweet already any thoughts on this?

**Comment by magro** [comment] 2016-05-10 18:47
Well, because writes are synchronized it should be safe as it is.

**Comment by maohui1993** [comment] 2016-05-12 11:12
well, I see see...

**Comment by magro** [comment] 2016-06-01 21:47
@maohui1993 can we close this issue?

**Closed** 2016-06-02 01:45 UTC
