### ISSUE TITLE
Fails serializing/deserializing some recursive relationships

### ISSUE THREAD

**Issue by johncurrier** [EsotericSoftware/kryo#710] opened 2020-02-06 23:55 UTC
I'm running into the following scenario:

Class Child contains:

1. Long id;
2. Parent parent;
3. int hashCode() { return id.hashCode(); }

Class Parent contains:

1. HashSet<Child> children;

An instance of Child gets serialized. In some instances Child.parent gets serialized prior to Child.id. When this occurs Parent's serialization seems to serialize an incomplete Child (with a null id).

During deserialization Parent gets deserialized, reconstructs children, and throws a NullPointerException in Child.hashCode() when trying to add the Child containing a null id to the children HashSet.

Note: if the id's field name alphabetically precedes "parent" then this works without an exception. If it alphabetically follows "parent" then it throws a NullPointerException.

My only thoughts on resolving this is for me to be able to specify how fields are ordered. In my scenario the ID fields are all annotated with an javax.persistence.Id and must be serialized first.

I've tried sorting fields in FieldSerializer, but I'm guessing that there are internal references to that ordering that merely reordering the array doesn't address.

Thoughts on letting us specify a field sort order (or alternatives)?

**Comment by johncurrier** [comment] 2020-02-07 01:14
Attaching test case:
[KryoNPETestcase.zip](https://github.com/EsotericSoftware/kryo/files/4168515/KryoNPETestcase.zip)

**Comment by theigl** [comment] 2020-05-25 10:56
I can reproduce your issue. Kryo currently always sorts fields by name to produce a stable ordering of fields because `Class.getDeclaredFields()` does not guarantee to return fields in a particular order. 

There are a couple of options to work around this:

1. Add a flag to `FieldSerializerConfig` that disables sorting by name. On OpenJDK and Oracle JVMs this should serialize fields in declaration order (although this is [not guaranteed](https://stackoverflow.com/a/5196561/441266)).
I experimentally added support for this on a branch and it resolves your issue but I'm not sure this is the way to go.

2. Allow users to sort fields themselves. `FieldSerializer` could add a `sortFields(Comparator<CachedField>)` method. You could then sort fields with `@javax.persistence.Id` first and then sort by name.

3. Add an `Order` annotation to `FieldSerializer` and let users declaratively define the order of fields. This would be the easiest to use solution, but also the most complex to implement and requires users to add Kryo annotations to their domain objects.

@johncurrier: What do you think about options 1 and 2? Both would be quite straight forward to implement.

**Comment by johncurrier** [comment] 2020-09-29 16:16
@theigl: I'm thinking that option 1 doesn't address the issue. We'd end up with somewhat random ordering that has no guarantee of being appropriate for the above scenario. Option 2 seems like the best choice.

**Comment by theigl** [comment] 2020-11-12 10:48
@johncurrier: I just realized that you should already be able to apply a custom sort order to fields: 

You can override `FieldSerializer.initializeCachedFields()`, retrieve the fields via `FieldSerializer.getFields()` and sort them as you like.

**Comment by johncurrier** [comment] 2020-11-13 17:11
Thanks for the suggestion. While implementing it I realized that it would
be simpler to just override *FieldSerializer.compare*, and that seems to
work. Do you have any concerns about that approach?

**Comment by theigl** [comment] 2020-11-13 20:05
@johncurrier: That's an even better idea! You should be alright as long as you always produce a stable ordering of fields.

**Comment by theigl** [comment] 2020-11-16 10:24
Closing this for now. If you need further help, please re-open.

**Closed by theigl** 2020-11-16 10:24 UTC
Labels: question
