### ISSUE TITLE
Module name changed between 5.0.0-RC9 and 5.0.0

### ISSUE THREAD

**Issue by Ahli** [EsotericSoftware/kryo#776] opened 2020-10-21 10:29 UTC
I had to edit the module-info.java in my project from:
`   requires com.esotericsoftware.kryo;      //5.0.0-RC9`
to:
`   requires kryo;      //5.0.0`

In google groups this was confirmed to be an unintended change: https://groups.google.com/g/kryo-users/c/dulDi8zUEEQ

**Comment by theigl** [comment] 2020-10-21 10:39
This issue is caused by upgrading to the latest version of the `maven-bundle-plugin` in #769.

A bug in that plugin drops the `Automatic-Module-Name` set by the `maven-jar-plugin`:
- https://issues.apache.org/jira/browse/FELIX-6312
- https://issues.apache.org/jira/browse/FELIX-6337

We should downgrade to version 4.x of the plugin until those issues are resolved.

**Comment by theigl** [comment] 2020-10-21 11:26
This will be fixed in 5.0.1.

**Closed** 2020-10-21 11:25 UTC
Labels: bug
